// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string leaderboard_hiscore = "CgkItKq_zYwPEAIQAQ"; // <GPGSID>
        public const string achievement_score__500 = "CgkItKq_zYwPEAIQCw"; // <GPGSID>
        public const string achievement_score__400 = "CgkItKq_zYwPEAIQCQ"; // <GPGSID>
        public const string achievement_score__300 = "CgkItKq_zYwPEAIQBw"; // <GPGSID>
        public const string achievement_score__200 = "CgkItKq_zYwPEAIQBQ"; // <GPGSID>
        public const string achievement_score__100 = "CgkItKq_zYwPEAIQAw"; // <GPGSID>
        public const string achievement_score__450 = "CgkItKq_zYwPEAIQCg"; // <GPGSID>
        public const string achievement_score__350 = "CgkItKq_zYwPEAIQCA"; // <GPGSID>
        public const string achievement_score__250 = "CgkItKq_zYwPEAIQBg"; // <GPGSID>
        public const string achievement_score__150 = "CgkItKq_zYwPEAIQBA"; // <GPGSID>
        public const string achievement_score__50 = "CgkItKq_zYwPEAIQAg"; // <GPGSID>

}

